url: http://pbardea.com
baseurl: 

# Site settings
title: Paul Bardea
email: paul@pbardea.com
description: "Hi, I'm Paul, a student of Software Engineering at the University of Waterloo."

# Color settings (hex-codes without the leading hash-tag)
color:
  #yellow
  #primary: fed136
  #yellow
  #secondary: fec503  
  #
  #red
  #primary: aa0000
  #red
  #secondary: 6a0000
  #
  #blue
  primary: 2399d4
  secondary: 1c79a8
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/pbardea
  - title: inbox
    url: mailto:paul@pbardea.com
  - title: camera
    url: http://www.500px.com/pbardea
  - title: linkedin
    url: http://www.linkedin.com/in/pbardea
  # - title: facebook
  #   url: #
  # - title: stack-overflow
  #   url: #http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/pbardea
  - title: twitter
    url: http://www.twitter.com/pbardea

# Build settings
markdown: kramdown
permalink: pretty
